# docker run --name nacos-quick -e MODE=standalone -p 8849:8848 -p 9848:9848 -p 9849:9849 -d nacos/nacos-server:2.3.1

version: '3.8'
name: 'nacos:v2.5.1'
services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - MODE=standalone
