# docker network create elastic
# docker run -d --name elasticsearch --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.17.28
# docker run -d --name kibana --net elastic -p 5601:5601 kibana:7.17.28

version: '3.8'
name: 'elasticsearch&kibana:7.17.28'
services:
  elastic:
    image: elasticsearch:7.17.28
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  kibana:
    image: kibana:7.17.28
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge

